### ISSUE TITLE
AWS::ImageBuilder::DistributionConfiguration - Distributions-AmiDistributionConfiguration-KmsKeyId

### ISSUE THREAD

**Issue by thomasklinger1234** [aws-cloudformation/cloudformation-coverage-roadmap#570] opened 2020-07-25 16:19 UTC
## 1. Title 

AWS::ImageBuilder::DistributionConfiguration-Distributions-AmiDistributionConfiguration-KmsKeyId

## 2. Scope of request 

**Scope**: new attribute for an existing resource is desired 

Add `KmsKeyId` property to support building encrypted images. This is a non-breaking addition to the existing `AWS::ImageBuilder::DistributionConfiguration` resource.

This will help us to migrate away from custom implementations as we are only permitted to use encrypted images. Now, we need to encrypt them in addition after being built.

Samples: 
## 3. Expected behavior

- When I add `KmsKeyId` property I will get an encrypted image
- When I omit `KmsKeyId` property I won't get an encrypted image
- Updates should require a new resource

## 4. Suggest specific test cases

- KmsKeyId provided
- KmsKeyId omitted

## 5. Helpful Links to speed up research and evaluation

- [Boto3 Docs for create_distribution_configuration](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/imagebuilder.html#imagebuilder.Client.create_distribution_configuration)

## 6. Category (required) - Will help with tagging and be easier to find by other users to +1

EC2 Image Builder.

**Comment by philchristensen** [comment] 2020-08-25 17:01
This is a major omission that really should be addressed ASAP. Is there any workaround?

**Comment by anderssoder** [comment] 2020-09-07 13:43
we need this as well

**Comment by wyuzheng** [comment] 2021-08-19 22:36
`AWS::ImageBuilder::DistributionConfiguration` has already supported `kmsKeyId` in the schema.

Here is the definition in `AWS::ImageBuilder::DistributionConfiguration` Github code base:
https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-imagebuilder/blob/master/distribution-configuration/aws-imagebuilder-distributionconfiguration.json#L52

The issue is ready be to closed as solved.

**Closed** 2021-08-20 00:02 UTC
Labels: Coverage
