### ISSUE TITLE
AWS::DMS::ReplicationInstance supports Tag property but cfn stack tags not propagating

### ISSUE THREAD

**Issue by jonnysaxon** [aws-cloudformation/cloudformation-coverage-roadmap#1252] opened 2022-07-28 04:03 UTC
### Name of the resource

AWS::DMS::ReplicationInstance

### Issue Description

It appears that ReplicationInstance supports the Tag property but the stack level tags are not propagating to these resources.

https://aws.amazon.com/premiumsupport/knowledge-center/cloudformation-propagate-stack-level-tag/

### Expected Behavior

I would expect the tags to propagate to the DMS replication instances

### Observed Behavior

No tags appear for the DMS replication instances

### Test Cases

Attached.

aws cloudformation create-stack \
                --stack-name dms-test \
                --capabilities 'CAPABILITY_IAM' \
                --template-body file://cf-dms.yml \
                --parameters file://parameters.json \
                --tags file://tags.json

### Other Details
[test-case.zip](https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/files/9214326/test-case.zip)

_No response_

**Comment by chevyye** [comment] 2022-12-23 22:21
Hi Andrew, if the tags you define in the AWS::DMS::ReplicationInstance resources has the same key and value pairs as the stack level tags, you should not need to remove your resource level tags manually.

**Comment by chevyye** [comment] 2022-12-23 22:25
The fix towards this bug has shipped. Closing this issue.

**Comment by chevyye** [comment] 2022-12-23 23:00
@jonnysaxon Hi Jonny, the issue is now resolved. We now make sure every cloudformation tags and stack tags will be added to replication instance. Let me know if you have any other question.

**Closed** 2022-12-24 00:03 UTC
Labels: bug
