### ISSUE TITLE
InternalFailure on `AWS::LakeFormation::PrincipalPermissions` resource

### ISSUE THREAD

**Issue by lucasvieirasilva** [aws-cloudformation/cloudformation-coverage-roadmap#1381] opened 2022-10-27 20:09 UTC
### Name of the resource

Other

### Resource Name

AWS::LakeFormation::PrincipalPermissions

### Issue Description

I'm having issues with the `AWS::LakeFormation::PrincipalPermissions` resource to grant permissions to lake formation tags for IAM roles.

The issue only happens when the permissions `ASSOCIATE` and `DESCRIBE` are used together, I've tested only with `DESCRIBE` or only `ASSOCIATE`, and both work okay.

CloudFormation Event Entry:
<img width="763" alt="image" src="https://user-images.githubusercontent.com/12723594/198386372-bc8eebb3-874d-457e-a2b6-08f5df17f894.png">

CloudFormation Resource:

```json
{
...
"PermissionMyRoleCategory": {
   "Type": "AWS::LakeFormation::PrincipalPermissions",
   "Properties": {
    "Permissions": [
     "ASSOCIATE",
     "DESCRIBE"
    ],
    "PermissionsWithGrantOption": [
     "ASSOCIATE",
     "DESCRIBE"
    ],
    "Principal": {
     "DataLakePrincipalIdentifier": "arn:aws:iam::123456789012:role/my-role"
    },
    "Resource": {
     "LFTag": {
      "CatalogId": "123456789012",
      "TagKey": "Category",
      "TagValues": [
       "*"
      ]
     }
    }
   }
  }
...
}
```

### Expected Behavior

The permissions should be granted and not fail the stack.

### Observed Behavior

- Only the `ASSOCIATE` works.
- Only the `DESCRIBE` works.
- Both together do not work.
- The resources are successfully created in the Lake Formation, but the stack fails and does not revoke the permissions.

### Test Cases

- Deploy a stack granting permissions on an LF Tag with `ASSOCIATE` and `DESCRIBE` at the same time, permissions to an IAM role.

**Comment by aws-gclend** [comment] 2022-10-29 00:56
Duplicate of #1323

**Closed** 2023-07-11 13:00 UTC
Labels: bug, NeedTriage
