### ISSUE TITLE
AWS::SES::Template - AWS::SES regional availability

### ISSUE THREAD

**Issue by iann0036** [aws-cloudformation/cloudformation-coverage-roadmap#326] opened 2020-01-06 05:10 UTC
**UPDATE:** For those coming across this issue, this applies to all AWS::SES::* resources across multiple regions

When uploading a template with an AWS::SES::Template resource in Sydney region, the following error is given:

```
Template format error: Unrecognized resource types: [AWS::SES::Template]
```

Categories: "other AWS services", "bug?"

**Comment by rjlohan** [comment] 2020-01-06 16:16
Not a bug, but a lagging deployment. We need to update our coverage to include the recent SES regions. That includes most of the types for the `AWS::SES` namespace (with the exception of `AWS::SES::ConfigurationSet` which is using the new Registry + CLI modelling). We are likely to migrate the other types to the new model before extending regional support. So, keep an eye on this [repository](https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-ses/settings).

**Comment by discobean** [comment] 2020-04-23 07:05
Is there any workaround for this?

**Comment by discobean** [comment] 2020-05-19 06:58
Just an FYI - I had a template in AWS that I'd deployed which had a condition, if ap-southeast-2 do not deploy the AWS::SES::Template Resource.

This worked when I deployed it, but then I went to update it (using `aws cloudformation deploy`), and got this error (even though the condition was still false):
```
An error occurred (ValidationError) when calling the GetTemplateSummary operation: Template format error: Unrecognized resource types: [AWS::SES::Template]
```

I could no longer update the template, and it was stuck.

The resolution was to run the template via `aws cloudformation create-change-set`
And then apply the changeset with `aws cloudformation execute-change-set`

I was then able to update the template.

**Comment by DrLuke** [comment] 2020-06-05 13:34
Is there any update on this? I just ran into the same issue. SES had new regions added quite a few months ago now.

**Comment by peterfotinis** [comment] 2020-10-20 04:38
Any update on this? 

If it helps anyone, my workaround for this is a CloudFormation custom resource that manually creates/updates/deletes the template in SES. The custom resource takes a "Template" parameter and passes it to the createTemplate method of the SES class (from aws-sdk). Working perfectly for our use case but it's still only a workaround

**Comment by peteristhegreat** [comment] 2020-10-20 15:59
Hitting this error on `eu-north-1`.

**Comment by alex-percayso** [comment] 2020-10-21 11:00
And in eu-west-2

**Comment by iann0036** [comment] 2020-10-28 00:26
Had to do the custom resource thing today for SES templates. Here's a sample for anyone looking:

```
Resources:

    LambdaServiceRole:
        Type: AWS::IAM::Role
        Properties:
            AssumeRolePolicyDocument:
                Version: '2012-10-17'
                Statement:
                  - Effect: Allow
                    Principal:
                        Service:
                          - lambda.amazonaws.com
                    Action:
                      - sts:AssumeRole
            Path: /
            Policies:
              - PolicyName: root
                PolicyDocument:
                    Version: '2012-10-17'
                    Statement:
                      - Effect: Allow
                        Action:
                          - logs:CreateLogGroup
                          - logs:CreateLogStream
                          - logs:PutLogEvents
                          - xray:PutTraceSegments
                          - xray:PutTelemetryRecords
                        Resource: '*'
                      - Effect: Allow
                        Action:
                          - ses:CreateTemplate
                          - ses:GetTemplate
                          - ses:UpdateTemplate
                          - ses:DeleteTemplate
                        Resource: "*"

    CustomResourceLambdaFunction:
        Type: AWS::Lambda::Function
        Properties:
            Handler: index.handler
            Role: !GetAtt LambdaServiceRole.Arn
            Code:
                ZipFile: |
                    import boto3
                    import os
                    import json
                    import cfnresponse
                    import pprint

                    def handler(event, context):
                        responseData = {}
                        try:
                            client = boto3.client('ses')
                            if event['RequestType'] == "Create":
                                pprint.pprint(client.create_template(
                                    Template={
                                        'TemplateName': event['ResourceProperties']['TemplateName'],
                                        'SubjectPart': event['ResourceProperties']['SubjectPart'],
                                        'TextPart': event['ResourceProperties']['TextPart'],
                                        'HtmlPart': event['ResourceProperties']['HtmlPart']
                                    }
                                ))
                            elif event['RequestType'] == "Update":
                                pprint.pprint(client.update_template(
                                    Template={
                                        'TemplateName': event['ResourceProperties']['TemplateName'],
                                        'SubjectPart': event['ResourceProperties']['SubjectPart'],
                                        'TextPart': event['ResourceProperties']['TextPart'],
                                        'HtmlPart': event['ResourceProperties']['HtmlPart']
                                    }
                                ))
                            elif event['RequestType'] == "Delete":
                                pprint.pprint(client.delete_template(
                                    TemplateName=event['ResourceProperties']['TemplateName']
                                ))
                            cfnresponse.send(event, context, cfnresponse.SUCCESS, responseData, "GenericPhysicalResourceId")
                        except:
                            cfnresponse.send(event, context, cfnresponse.FAILED, responseData, "GenericPhysicalResourceId")

            Runtime: python3.7
            Timeout: 30

    WelcomeTemplate:
        Type: Custom::Template
        Properties:
            ServiceToken: !GetAtt CustomResourceLambdaFunction.Arn
            TemplateName: "welcome"
            SubjectPart: "Welcome to the application!"
            TextPart: |
                Hey {{firstname}},

                Welcome to the application.

                - The Team
            HtmlPart: |
                Hey {{firstname}},<br /><br />

                Welcome to the application.<br /><br />

                - The Team

```

**Comment by henning-krause** [comment] 2020-11-06 14:40
Same here... eu-central-1

**Comment by aloknew** [comment] 2020-12-11 17:40
Request you to take this up on priority, Not able to create these in Canada Frankfurt and Sydney Region

**Comment by cnase** [comment] 2020-12-11 19:25
Is there an ETA on this?  This causes a major headache in our deployment and the "workarounds" are ugly.

**Comment by Hikaon** [comment] 2021-01-21 15:08
Lazy workaround:

**Comment by saidaisri** [comment] 2021-02-14 17:11
And in ap-south-1

**Comment by JamaicanFriedChicken** [comment] 2021-04-07 03:29
Currentl still unavailable for ca-central-1

**Comment by volodymyrrudyi** [comment] 2021-04-18 11:33
This is still an issue in eu-west-2

**Comment by ronancunningham72** [comment] 2021-05-14 16:00
still on eu-west-2, that's pretty poor

**Comment by seemantk-schweitzer** [comment] 2021-05-22 03:46
this ticket has been open for a year and a half now, and we'd love an update on some ETAs please.  Either regarding the new registry + cli modelling migration for this, or for regional support for the existing model.  Where is this on the CFN team's priority list, please?  SES is a very important need

**Comment by mhemmings** [comment] 2021-06-09 11:59
@rjlohan @PatMyron Any update on the deployment lag? Could we get the docs updated to mention the current issues across regions, so that failures don't crop up unexpectedly for others? (This will appear to users as a pretty serious bug without that documentation)

**Comment by seemantk-schweitzer** [comment] 2021-06-09 12:33
Thank you. To be honest, this is a serious bug even with the documentation.  All the documentation will do is a "cover our ass" thing, whereas the frustration in this entire ticket is that the deployment is lagging and there's little indication that the SES/CloudFormation effort is moving.

So, respectfully, rather than writing documentation to tell us which regions are supported, please just support all the regions.

**Comment by cvanes** [comment] 2021-06-29 23:14
Any ETA for when this might be available?

**Comment by kyanet** [comment] 2021-08-07 13:41
same issue in ap-northeast-1

**Comment by LucasSubli** [comment] 2021-08-22 05:13
same issue in us-east-2

**Comment by iann0036** [comment] 2021-08-25 10:35
This is not shipped. Please reopen.

**Comment by modul** [comment] 2021-11-12 14:40
Is there any update for this? I'd really like to use this feature but Cloudformation is holding me back …

**Comment by labarilem** [comment] 2021-11-12 14:49
As a workaround, I quickly hacked together this Node.js script:

```js
const fs = require('fs');
const path = require('path');
const execSync = require('child_process').execSync;

const templatesDir = './email-templates/ses';
for (const file of fs.readdirSync(templatesDir)) {
  const filePath = path.join(templatesDir, file);
  if (fs.lstatSync(filePath).isFile() && filePath.endsWith('.yml')) {
    try {
      const updateCode = execSync('aws ses update-template --cli-input-yaml "file://email-templates/ses/' + file + '"');
      console.log('updated ' + file);
    } catch (err) {
      // Failed to update
      try {
        const createCode = execSync('aws ses create-template --cli-input-yaml "file://email-templates/ses/' + file + '"');
        console.log('created ' + file);
      } catch (err2) {
        console.error(err);
        console.error(err2);
      }
    }
  }
}
```

Basically I'm putting my email templates (yml files) in a folder and the script tries to run an update-template for each file. If it fails, it runs a create-template.

The script needs some changes to also support templates deletion. I'll probably do it when I need that feature.

**Comment by KittieHearts** [comment] 2021-12-22 00:51
Has there been any update on this for ses sydney region?
I am still having issues

**Comment by sthulb** [comment] 2022-01-06 08:41
🎵 Happy birthday to you! Happy birthday to you! 🎵

![DE2C4EC0-5AB4-45C9-85DC-3F21D0BA4353](https://user-images.githubusercontent.com/103217/148354609-cefb00fd-fd20-4991-9b77-5017e5d10887.jpeg)

**Comment by mgamsjager** [comment] 2022-01-25 09:31
Any updates on eu-central-1?

**Comment by WillzMu** [comment] 2022-01-31 14:42
Looks like its still not available for eu-central-1.

**Comment by BKSnake** [comment] 2022-02-07 09:02
Do you have any updates for us-east-2

I'm getting `The CloudFormation template is invalid: ValidationError: Template format error: Unrecognized resource types: [AWS::SES::Template]` when i'm trying to deploy template

**Comment by HEBayoumy** [comment] 2022-02-08 22:40
Hey all, thank you very much for sharing your feedback, we really appreciate it. We're actively working on implementing this and will update you once it's merged.

**Comment by HEBayoumy** [comment] 2022-02-23 12:21
AWS::SES::Template is available now in all regions where SES is. Other SES resources are available as well as of yesterday:
AWS::SES::ConfigurationSetEventDestination
AWS::SES::ConfigurationSet
AWS::SES::ContactList

Please continue sharing your feedback we really appreciate it.

**Closed** 2022-03-04 21:01 UTC
Labels: other AWS services, regional parity, Coverage

**Comment by patspam** [comment] 2023-01-28 09:26
Same issue again in the new `ap-southeast-4` region
