### ISSUE TITLE
AWS::Events::EventBusPolicy - [BUG] Resource Type AWS::Event::EventBusPolicy has a Condition property which causes internal failures in change sets

### ISSUE THREAD

**Issue by badaldavda** [aws-cloudformation/cloudformation-coverage-roadmap#156] opened 2019-09-04 04:57 UTC
Summary
============
In CreateChangeSet, a "Condition" in a resource "Properties" is an invalid behavior currently and will cause an internal failure, looks like it is a long-running issue and been discovered.

Example Template:
------------------------
Resources:
SampleEventBusPolicy: 
Type: AWS::Events::EventBusPolicy
Properties: 
Action: "events:PutEvents"
Principal: "*"
StatementId: "DemoStatement2"
Condition: 
Type: "true"
Key: "aws:PrincipalOrgID"
Value: "o-1234567890"

There is already a bug reported in internal issues. It would really be the best if the same could be added in the roadmap so that its easy to track.

**Comment by lazharichir** [comment] 2020-02-04 16:58
Still facing this (using CDK):

```
{
	"companyeventbuspolicy": {
		"Type": "AWS::Events::EventBusPolicy",
		"Properties": {
			"Action": "events:PutEvents",
			"Principal": "*",
			"StatementId": "company-event-bus-policy-statement",
			"Condition": {
				"Key": "aws:PrincipalOrgID",
				"Type": "StringEquals",
				"Value": "o-123456789"
			},
			"EventBusName": {
				"Ref": "companyeventbus9ABF23AA"
			}
		},
		"Metadata": {
			"aws:cdk:path": "company-events-stack/company-event-bus-policy"
		}
	}
}
```

**Comment by szotrj** [comment] 2020-06-12 04:15
Just spent hours troubleshooting this with an open AWS Enterprise Support case.

My template snippet:
```yaml
Resources:
  rEventBusPolicy:
    Type: 'AWS::Events::EventBusPolicy'
    Properties:
      Action: 'events:PutEvents'
      Principal: '*'
      StatementId: Organization
      Condition:
        Type: StringEquals
        Key: 'aws:PrincipalOrgID'
        Value:
          Fn::FindInMap:
            - OrgMap
            - !Ref AWS::Partition
            - ORG
```

**Comment by ashwanijha04** [comment] 2020-07-02 08:12
The problem here is with the CreateChangeSet API call. 

'**aws cloudformation deploy**' command creates a **changeset** before creating or updating the stack as mentioned in the doc[2].

_"Deploys the specified AWS CloudFormation template by creating and then executing a change set"_

The current workaround is to use the '**aws cloudformation create-stack**' CLI command **instead of** '**_aws cloudformation deploy_**' until this is fixed:

**`aws cloudformation create-stack --stack-name myBug --template-body file://bug_test.yaml`**


_[1] deploy
     https://docs.aws.amazon.com/cli/latest/reference/cloudformation/deploy/index.html#deploy_

_[2] create-stack:
    https://docs.aws.amazon.com/cli/latest/reference/cloudformation/create-stack.html_

**Comment by dejonghe** [comment] 2020-07-24 19:18
This is blocking my team as well. How has this gone almost a year with no AWS Acknowledgement?

**Comment by chmoora** [comment] 2020-07-28 09:36
Dear CFN team, any updates on this? It's been almost a year. This currently blocks CDK issue below.

https://github.com/aws/aws-cdk/issues/1785

**Comment by nbrational** [comment] 2020-08-09 13:51
I have tried to put together a workaround using CloudFormation custom resource which has parameter called 'TheCondition' instead of 'Condition' as the latter collides with CloudFormation intrinsic function. Change Set creation works fine:- https://github.com/nbrational/CFN_EventBusPolicy_Bug156

**Comment by ALutchko** [comment] 2022-06-27 11:20
Almost three years :(

**Comment by nikp** [comment] 2022-07-30 03:24
Thanks everyone for your patience. @badaldavda as you probably already discovered, there was a bug in your initial CFN yaml

```yaml
Condition:
  Type: "true"
  Key: "aws:PrincipalOrgID"
  Value: "o-1234567890"
```

should have been

```yaml
Condition:
  Type: "StringEquals"
  Key: "aws:PrincipalOrgID"
  Value: "o-1234567890"
```

Other folks including @lazharichir and @szotrj had the correct syntax, but ran into another issue that CFN team fixed in September 2020.

In our testing today we were unable to reproduce this issue. Is it still something that you're facing?

**Comment by ALutchko** [comment] 2022-07-30 03:36
I found a way to make it much simpler and clear:
```
Condition:
          StringEquals:
            "aws:PrincipalOrgID": !Ref OrgId
```

**Comment by gussotoridd** [comment] 2022-08-03 23:47
The issue is reproduced with the following bash commands, and no longer reproducible. (Account used is obfuscated)

### Template files for use

```bash
cat template_no_condition.yaml                                                                
Resources:
  rEventBusPolicy:
    Type: 'AWS::Events::EventBusPolicy'
    Properties:
      Action: 'events:PutEvents'
      Principal: '*'
      StatementId: Organization


cat template_with_condition.yaml 
Resources:
  rEventBusPolicy:
    Type: 'AWS::Events::EventBusPolicy'
    Properties:
      Action: 'events:PutEvents'
      Principal: '*'
      StatementId: Organization
      Condition:
        Type: StringEquals
        Key: 'aws:PrincipalOrgID'
        Value: 'o-1234567890'
```        

### Create stack        

```bash
aws cloudformation create-stack --stack-name Github-156 --template-body file://template_no_condition.yaml


{
    "StackId": "arn:aws:cloudformation:us-west-2:************:stack/Github-156/cfe52d60-1383-11ed-8af8-02c4d2ce0ebf"
}
```


### Describe stack events

```bash
aws cloudformation describe-stack-events --stack-name Github-156

{
    "StackEvents": [
        {
            "StackId": "arn:aws:cloudformation:us-west-2:************:stack/Github-156/cfe52d60-1383-11ed-8af8-02c4d2ce0ebf",
            "EventId": "d45fb900-1383-11ed-b211-0ab70601f9df",
            "StackName": "Github-156",
            "LogicalResourceId": "Github-156",
            "PhysicalResourceId": "arn:aws:cloudformation:us-west-2:************:stack/Github-156/cfe52d60-1383-11ed-8af8-02c4d2ce0ebf",
            "ResourceType": "AWS::CloudFormation::Stack",
            "Timestamp": "2022-08-03T23:27:24.296000+00:00",
            "ResourceStatus": "CREATE_COMPLETE"
        },
        {
            "StackId": "arn:aws:cloudformation:us-west-2:************:stack/Github-156/cfe52d60-1383-11ed-8af8-02c4d2ce0ebf",
            "EventId": "rEventBusPolicy-CREATE_COMPLETE-2022-08-03T23:27:23.270Z",
            "StackName": "Github-156",
            "LogicalResourceId": "rEventBusPolicy",
            "PhysicalResourceId": "EventBusPolicy-PdWn7n8Ut3VA",
            "ResourceType": "AWS::Events::EventBusPolicy",
            "Timestamp": "2022-08-03T23:27:23.270000+00:00",
            "ResourceStatus": "CREATE_COMPLETE",
            "ResourceProperties": "{\"Action\":\"events:PutEvents\",\"StatementId\":\"Organization\",\"Principal\":\"*\"}"
        },
        {
            "StackId": "arn:aws:cloudformation:us-west-2:************:stack/Github-156/cfe52d60-1383-11ed-8af8-02c4d2ce0ebf",
            "EventId": "rEventBusPolicy-CREATE_IN_PROGRESS-2022-08-03T23:27:23.112Z",
            "StackName": "Github-156",
            "LogicalResourceId": "rEventBusPolicy",
            "PhysicalResourceId": "EventBusPolicy-PdWn7n8Ut3VA",
            "ResourceType": "AWS::Events::EventBusPolicy",
            "Timestamp": "2022-08-03T23:27:23.112000+00:00",
            "ResourceStatus": "CREATE_IN_PROGRESS",
            "ResourceStatusReason": "Resource creation Initiated",
            "ResourceProperties": "{\"Action\":\"events:PutEvents\",\"StatementId\":\"Organization\",\"Principal\":\"*\"}"
        },
        {
            "StackId": "arn:aws:cloudformation:us-west-2:************:stack/Github-156/cfe52d60-1383-11ed-8af8-02c4d2ce0ebf",
            "EventId": "rEventBusPolicy-CREATE_IN_PROGRESS-2022-08-03T23:27:21.120Z",
            "StackName": "Github-156",
            "LogicalResourceId": "rEventBusPolicy",
            "PhysicalResourceId": "",
            "ResourceType": "AWS::Events::EventBusPolicy",
            "Timestamp": "2022-08-03T23:27:21.120000+00:00",
            "ResourceStatus": "CREATE_IN_PROGRESS",
            "ResourceProperties": "{\"Action\":\"events:PutEvents\",\"StatementId\":\"Organization\",\"Principal\":\"*\"}"
        },
        {
            "StackId": "arn:aws:cloudformation:us-west-2:************:stack/Github-156/cfe52d60-1383-11ed-8af8-02c4d2ce0ebf",
            "EventId": "cfe6b400-1383-11ed-8af8-02c4d2ce0ebf",
            "StackName": "Github-156",
            "LogicalResourceId": "Github-156",
            "PhysicalResourceId": "arn:aws:cloudformation:us-west-2:************:stack/Github-156/cfe52d60-1383-11ed-8af8-02c4d2ce0ebf",
            "ResourceType": "AWS::CloudFormation::Stack",
            "Timestamp": "2022-08-03T23:27:16.831000+00:00",
            "ResourceStatus": "CREATE_IN_PROGRESS",
            "ResourceStatusReason": "User Initiated"
        }
    ]
}
```


### Create changeset to add condition

```bash
aws cloudformation create-change-set --stack-name Github-156 --change-set-name changeSet1 --template-body file://template_with_condition.yaml

{
    "Id": "arn:aws:cloudformation:us-west-2:************:changeSet/changeSet1/c6438808-63cd-43c9-8271-2445626701f9",
    "StackId": "arn:aws:cloudformation:us-west-2:************:stack/Github-156/cfe52d60-1383-11ed-8af8-02c4d2ce0ebf"
}
```

### Describe changeset

```bash
aws cloudformation describe-change-set --stack-name Github-156 --change-set-name changeSet1

{
    "Changes": [
        {
            "Type": "Resource",
            "ResourceChange": {
                "Action": "Modify",
                "LogicalResourceId": "rEventBusPolicy",
                "PhysicalResourceId": "EventBusPolicy-PdWn7n8Ut3VA",
                "ResourceType": "AWS::Events::EventBusPolicy",
                "Replacement": "Conditional",
                "Scope": [
                    "Properties"
                ],
                "Details": [
                    {
                        "Target": {
                            "Attribute": "Properties",
                            "Name": "Condition",
                            "RequiresRecreation": "Conditionally"
                        },
                        "Evaluation": "Static",
                        "ChangeSource": "DirectModification"
                    }
                ]
            }
        }
    ],
    "ChangeSetName": "changeSet1",
    "ChangeSetId": "arn:aws:cloudformation:us-west-2:************:changeSet/changeSet1/c6438808-63cd-43c9-8271-2445626701f9",
    "StackId": "arn:aws:cloudformation:us-west-2:************:stack/Github-156/cfe52d60-1383-11ed-8af8-02c4d2ce0ebf",
    "StackName": "Github-156",
    "Description": null,
    "Parameters": null,
    "CreationTime": "2022-08-03T23:33:11.564000+00:00",
    "ExecutionStatus": "AVAILABLE",
    "Status": "CREATE_COMPLETE",
    "StatusReason": null,
    "NotificationARNs": [],
    "RollbackConfiguration": {},
    "Capabilities": [],
    "Tags": null,
    "ParentChangeSetId": null,
    "IncludeNestedStacks": false,
    "RootChangeSetId": null
}
```


### Execute changeset
```bash
aws cloudformation execute-change-set --stack-name Github-156 --change-set-name changeSet1
```

### Describe changeset (again)

```bash
aws cloudformation describe-change-set --stack-name Github-156 --change-set-name changeSet1

An error occurred (ChangeSetNotFound) when calling the DescribeChangeSet operation: ChangeSet [changeSet1] does not exist
```

### Describe stack events
```bash
aws cloudformation describe-stack-events --stack-name Github-156

{
    "StackEvents": [
        {
            "StackId": "arn:aws:cloudformation:us-west-2:************:stack/Github-156/cfe52d60-1383-11ed-8af8-02c4d2ce0ebf",
            "EventId": "f8dda700-1384-11ed-92bd-0633e6acc595",
            "StackName": "Github-156",
            "LogicalResourceId": "Github-156",
            "PhysicalResourceId": "arn:aws:cloudformation:us-west-2:************:stack/Github-156/cfe52d60-1383-11ed-8af8-02c4d2ce0ebf",
            "ResourceType": "AWS::CloudFormation::Stack",
            "Timestamp": "2022-08-03T23:35:35.016000+00:00",
            "ResourceStatus": "UPDATE_COMPLETE"
        },
        {
            "StackId": "arn:aws:cloudformation:us-west-2:************:stack/Github-156/cfe52d60-1383-11ed-8af8-02c4d2ce0ebf",
            "EventId": "f861c040-1384-11ed-8298-024d8e870689",
            "StackName": "Github-156",
            "LogicalResourceId": "Github-156",
            "PhysicalResourceId": "arn:aws:cloudformation:us-west-2:************:stack/Github-156/cfe52d60-1383-11ed-8af8-02c4d2ce0ebf",
            "ResourceType": "AWS::CloudFormation::Stack",
            "Timestamp": "2022-08-03T23:35:34.207000+00:00",
            "ResourceStatus": "UPDATE_COMPLETE_CLEANUP_IN_PROGRESS"
        },
        {
            "StackId": "arn:aws:cloudformation:us-west-2:************:stack/Github-156/cfe52d60-1383-11ed-8af8-02c4d2ce0ebf",
            "EventId": "rEventBusPolicy-UPDATE_COMPLETE-2022-08-03T23:35:32.816Z",
            "StackName": "Github-156",
            "LogicalResourceId": "rEventBusPolicy",
            "PhysicalResourceId": "EventBusPolicy-6ac8isnWizra",
            "ResourceType": "AWS::Events::EventBusPolicy",
            "Timestamp": "2022-08-03T23:35:32.816000+00:00",
            "ResourceStatus": "UPDATE_COMPLETE",
            "ResourceProperties": "{\"Condition\":{\"Type\":\"StringEquals\",\"Value\":\"o-1234567890\",\"Key\":\"aws:PrincipalOrgID\"},\"Action\":\"events:PutEvents\",\"StatementId\":\"Organization\",\"Principal\":\"*\"}"
        },
        {
            "StackId": "arn:aws:cloudformation:us-west-2:************:stack/Github-156/cfe52d60-1383-11ed-8af8-02c4d2ce0ebf",
            "EventId": "rEventBusPolicy-UPDATE_IN_PROGRESS-2022-08-03T23:35:31.287Z",
            "StackName": "Github-156",
            "LogicalResourceId": "rEventBusPolicy",
            "PhysicalResourceId": "EventBusPolicy-PdWn7n8Ut3VA",
            "ResourceType": "AWS::Events::EventBusPolicy",
            "Timestamp": "2022-08-03T23:35:31.287000+00:00",
            "ResourceStatus": "UPDATE_IN_PROGRESS",
            "ResourceProperties": "{\"Condition\":{\"Type\":\"StringEquals\",\"Value\":\"o-1234567890\",\"Key\":\"aws:PrincipalOrgID\"},\"Action\":\"events:PutEvents\",\"StatementId\":\"Organization\",\"Principal\":\"*\"}"
        },
        {
            "StackId": "arn:aws:cloudformation:us-west-2:************:stack/Github-156/cfe52d60-1383-11ed-8af8-02c4d2ce0ebf",
            "EventId": "f31b8030-1384-11ed-85c8-02558c15bc53",
            "StackName": "Github-156",
            "LogicalResourceId": "Github-156",
            "PhysicalResourceId": "arn:aws:cloudformation:us-west-2:************:stack/Github-156/cfe52d60-1383-11ed-8af8-02c4d2ce0ebf",
            "ResourceType": "AWS::CloudFormation::Stack",
            "Timestamp": "2022-08-03T23:35:25.359000+00:00",
            "ResourceStatus": "UPDATE_IN_PROGRESS",
            "ResourceStatusReason": "User Initiated"
        },
        {
            "StackId": "arn:aws:cloudformation:us-west-2:************:stack/Github-156/cfe52d60-1383-11ed-8af8-02c4d2ce0ebf",
            "EventId": "d45fb900-1383-11ed-b211-0ab70601f9df",
            "StackName": "Github-156",
            "LogicalResourceId": "Github-156",
            "PhysicalResourceId": "arn:aws:cloudformation:us-west-2:************:stack/Github-156/cfe52d60-1383-11ed-8af8-02c4d2ce0ebf",
            "ResourceType": "AWS::CloudFormation::Stack",
            "Timestamp": "2022-08-03T23:27:24.296000+00:00",
            "ResourceStatus": "CREATE_COMPLETE"
        },
        {
            "StackId": "arn:aws:cloudformation:us-west-2:************:stack/Github-156/cfe52d60-1383-11ed-8af8-02c4d2ce0ebf",
            "EventId": "rEventBusPolicy-CREATE_COMPLETE-2022-08-03T23:27:23.270Z",
            "StackName": "Github-156",
            "LogicalResourceId": "rEventBusPolicy",
            "PhysicalResourceId": "EventBusPolicy-PdWn7n8Ut3VA",
            "ResourceType": "AWS::Events::EventBusPolicy",
            "Timestamp": "2022-08-03T23:27:23.270000+00:00",
            "ResourceStatus": "CREATE_COMPLETE",
            "ResourceProperties": "{\"Action\":\"events:PutEvents\",\"StatementId\":\"Organization\",\"Principal\":\"*\"}"
        },
        {
            "StackId": "arn:aws:cloudformation:us-west-2:************:stack/Github-156/cfe52d60-1383-11ed-8af8-02c4d2ce0ebf",
            "EventId": "rEventBusPolicy-CREATE_IN_PROGRESS-2022-08-03T23:27:23.112Z",
            "StackName": "Github-156",
            "LogicalResourceId": "rEventBusPolicy",
            "PhysicalResourceId": "EventBusPolicy-PdWn7n8Ut3VA",
            "ResourceType": "AWS::Events::EventBusPolicy",
            "Timestamp": "2022-08-03T23:27:23.112000+00:00",
            "ResourceStatus": "CREATE_IN_PROGRESS",
            "ResourceStatusReason": "Resource creation Initiated",
            "ResourceProperties": "{\"Action\":\"events:PutEvents\",\"StatementId\":\"Organization\",\"Principal\":\"*\"}"
        },
        {
            "StackId": "arn:aws:cloudformation:us-west-2:************:stack/Github-156/cfe52d60-1383-11ed-8af8-02c4d2ce0ebf",
            "EventId": "rEventBusPolicy-CREATE_IN_PROGRESS-2022-08-03T23:27:21.120Z",
            "StackName": "Github-156",
            "LogicalResourceId": "rEventBusPolicy",
            "PhysicalResourceId": "",
            "ResourceType": "AWS::Events::EventBusPolicy",
            "Timestamp": "2022-08-03T23:27:21.120000+00:00",
            "ResourceStatus": "CREATE_IN_PROGRESS",
            "ResourceProperties": "{\"Action\":\"events:PutEvents\",\"StatementId\":\"Organization\",\"Principal\":\"*\"}"
        },
        {
            "StackId": "arn:aws:cloudformation:us-west-2:************:stack/Github-156/cfe52d60-1383-11ed-8af8-02c4d2ce0ebf",
            "EventId": "cfe6b400-1383-11ed-8af8-02c4d2ce0ebf",
            "StackName": "Github-156",
            "LogicalResourceId": "Github-156",
            "PhysicalResourceId": "arn:aws:cloudformation:us-west-2:************:stack/Github-156/cfe52d60-1383-11ed-8af8-02c4d2ce0ebf",
            "ResourceType": "AWS::CloudFormation::Stack",
            "Timestamp": "2022-08-03T23:27:16.831000+00:00",
            "ResourceStatus": "CREATE_IN_PROGRESS",
            "ResourceStatusReason": "User Initiated"
        }
    ]
}
```

### Describe stacks

```bash
aws cloudformation describe-stacks --stack-name Github-156

{
    "Stacks": [
        {
            "StackId": "arn:aws:cloudformation:us-west-2:************:stack/Github-156/cfe52d60-1383-11ed-8af8-02c4d2ce0ebf",
            "StackName": "Github-156",
            "ChangeSetId": "arn:aws:cloudformation:us-west-2:************:changeSet/changeSet1/c6438808-63cd-43c9-8271-2445626701f9",
            "CreationTime": "2022-08-03T23:27:16.831000+00:00",
            "LastUpdatedTime": "2022-08-03T23:35:25.359000+00:00",
            "RollbackConfiguration": {},
            "StackStatus": "UPDATE_COMPLETE",
            "DisableRollback": false,
            "NotificationARNs": [],
            "Tags": [],
            "EnableTerminationProtection": false,
            "DriftInformation": {
                "StackDriftStatus": "NOT_CHECKED"
            }
        }
    ]
}
```

**Closed** 2022-08-04 00:01 UTC
Labels: Coverage
