### ISSUE TITLE
Support Amazon SQS key (SSE-SQS) encryption at rest

### ISSUE THREAD

**Issue by GrahamCampbell** [aws-cloudformation/cloudformation-coverage-roadmap#1011] opened 2021-12-20 03:06 UTC
### Name of the resource

AWS::SQS::Queue

### Description

Currently CloudFormation only supports SSE-KMS, but the SQS service team recently added support for SQS-managed encryption at rest. This doesn't seem to have made it's way into CloudFormation yet. Documentation is available at https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-server-side-encryption.html and https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-configure-sqs-sse-queue.html. The `CreateQueue` and `SetQueueAttributes` actions implements this as a `"SqsManagedSseEnabled"` attribute with value `"true"` https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_CreateQueue.html#API_CreateQueue_RequestParameters.

<img width="783" alt="image" src="https://user-images.githubusercontent.com/2829600/146705281-00d06a7e-31ac-4953-9379-998e71cce1b7.png">

### Other Details

Related tickets for this implemented for Dynamo: https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/5.

**Comment by parraletz** [comment] 2021-12-20 14:27
I think this is the same https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/989#issue-1064213865

**Comment by WaelA** [comment] 2022-04-20 17:41
Looks like duplicate of https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/989

**Closed by WaelA** 2022-04-20 17:41 UTC
Labels: Coverage
