### ISSUE TITLE
AWS::Route53Resolver::ResolverEndpoint - Add ipAddresses as a return attribute

### ISSUE THREAD

**Issue by guidola** [aws-cloudformation/cloudformation-coverage-roadmap#600] opened 2020-08-07 09:04 UTC
## 2. Scope of request 

AWS::Route53::ResolverEndpoint should have an additional return attribute that can be later fetched through the !GetAtt function which allows to retrieve the ip addresses of the created ENIs.

This would allow to dynamically tie other resources that may use those values as part of their configuration such as a AWS::EC2:VpnClientEndpoint

## 3. Expected behavior

Calling `!GetAtt inboundEnpoint.ipAddresses` would return an array containing the ip addresses available for resolution.

## 6. Category (required) 
4.  Networking & Content (VPC, Route53, API GW,...)

**Comment by 2018ik** [comment] 2021-11-11 15:53
Duplicate of #172

**Closed** 2021-11-11 17:02 UTC
Labels: Coverage
