### ISSUE TITLE
Cloudformation API call to OpenSearch included invalid parameter

### ISSUE THREAD

**Issue by FrankShorty** [aws-cloudformation/cloudformation-coverage-roadmap#1496] opened 2023-01-23 14:29 UTC
### Name of the resource

AWS::OpenSearchService::Domain

### Issue Description

When calling the OS API from CloudFormation, an attribute is added that is not supported.

Under the advanced Security Options, the attribute sAMLOptions is added:
```

        "advancedSecurityOptions": {
            "enabled": true,
            "internalUserDatabaseEnabled": true,
            "masterUserOptions": {
                "masterUserName": "HIDDEN_DUE_TO_SECURITY_REASONS",
                "masterUserPassword": "HIDDEN_DUE_TO_SECURITY_REASONS"
            },
            "sAMLOptions": {
                "enabled": false
            }
        }
```

This throws an error:
You cannot specify SAML options during domain creation

### Expected Behavior

The API call last week did not contain this value:

```
 "advancedSecurityOptions": {
            "enabled": true,
            "internalUserDatabaseEnabled": true,
            "masterUserOptions": {
                "masterUserName": "HIDDEN_DUE_TO_SECURITY_REASONS",
                "masterUserPassword": "HIDDEN_DUE_TO_SECURITY_REASONS"
            }
        }
```

I would expect the API call to work as no changes to the template were made.

### Observed Behavior

The API fails with an error message rather than create the domain.

### Test Cases

Try to create a new OS domain using Cloudformation, specifying the AdvancedSecurityOptions.

**Comment by FrankShorty** [comment] 2023-01-23 14:36
Possibly related to 
https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/1288

**Comment by devardee** [comment] 2023-01-27 09:15
the issue is resolved now. @FrankShorty , can you pls confirm ?

**Comment by FrankShorty** [comment] 2023-01-27 09:32
Hi,

Thanks, just tested, I can deploy OS from CFN again!

Thank you for the speedy work!

Frank

**Comment by devardee** [comment] 2023-02-07 13:53
@FrankShorty , can you close this issue ?

**Closed** 2023-03-10 13:03 UTC
Labels: bug
