### ISSUE TITLE
AWS::Route53Resolver::ResolverRule - Cloudformation does not support to update tags on Route53 Resolver and Route53 resolver rules

### ISSUE THREAD

**Issue by bbergero** [aws-cloudformation/cloudformation-coverage-roadmap#536] opened 2020-06-24 14:21 UTC
```
{
  "Type" : "AWS::EC2::LocalGatewayRouteTableVPCAssociation",
  "Properties" : {
      "LocalGatewayRouteTableId" : String,
      "Tags" : Tags,
      "VpcId" : String
    }
}
```
same for 
```
{
  "Type" : "AWS::Route53Resolver::ResolverEndpoint",
  "Properties" : {
      "Direction" : String,
      "IpAddresses" : [ IpAddressRequest, ... ],
      "Name" : String,
      "SecurityGroupIds" : [ String, ... ],
      "Tags" : [ Tag, ... ]
    }
}
```
2. Scope of request -> if you change Tags value and run an stack update Tags are not getting updated
3. Expected behavior -> 
submit stack for an update where
```
"Type" : "AWS::EC2::LocalGatewayRouteTableVPCAssociation",
  "Properties" : {
      "LocalGatewayRouteTableId" : String,
      "Tags" : NEWTags,
      "VpcId" : String
    }
}
```
we expect the tags to be change to "
NEWTags"
4. Test case recommendation (optional) -> it should help me do X given existing Y (if applicable); it should/shouldn't

**Comment by 2018ik** [comment] 2021-11-11 15:52
Duplicate of #696

**Closed** 2021-11-11 16:02 UTC
Labels: Coverage
