### ISSUE TITLE
Drift Detection issue for Classic property under AWS::Redshift::Cluster resource

### ISSUE THREAD

**Issue by amedeshm** [aws-cloudformation/cloudformation-coverage-roadmap#1204] opened 2022-06-08 00:11 UTC
### Name of the resource

AWS::Redshift::Cluster

### Issue Description

The `Classic` property for the AWS::Redshift::Cluster resource is marked as drifted when its value is specified as `false`. 

### Expected Behavior

The `Classic` property should be IN_SYNC or NOT_CHECKED status.

### Observed Behavior

The `Classic` property is marked as REMOVE with
expected = false
actual = -

### Test Cases

Steps to reproduce -

1) Create Stack using following template -
```
Resources:
    myCluster:
      Type: 'AWS::Redshift::Cluster'
      Properties:
        DBName: mydb
        MasterUsername: master
        MasterUserPassword: xxxxxxxxxx
        NodeType: ds2.xlarge
        ClusterType: single-node
        Classic: false
```
2) Run drift detection
3) View drift results

**Comment by shwetayakkali** [comment] 2022-07-22 19:52
classic property indicates A boolean value indicating whether the resize operation is using the classic resize

sometimes customer may remove this value when modification/update in terms of resize is done, this isn't a core param for cluster, added to ease cloudformation template to indicate classic resize. describe-clusters used in drift will not indicate this property and hence this property once used in updating should be removed. We can resolve this ticket imo.
Will get in touch with docs team to document this case for Redshift cluster drift.

**Comment by shwetayakkali** [comment] 2022-10-25 18:16
https://i.amazon.com/issues/CFN-44852 to ignore this property

**Comment by rgoltz** [comment] 2022-11-06 14:34
Hi @shwetayakkali - Thanks a lot for the provided information. Unfortunately, we still see a drift reported if we set `Classic` property to `false` in CFN template. Having this said, the property seems not to be ignored (tested in eu-central-1).

Could you please re-open this issue here? (or should I create a new issue with reference to this?)

**Comment by greg5123334** [comment] 2022-12-11 06:28
Confirmed. This behavior is consistently reproducible. The '[classic](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-redshift-cluster.html#cfn-redshift-cluster-classic)' property is reporting false-positive drift, regardless of the value.

Test code:

>         key = kms.Key(self, "MyKey",
>                       removal_policy=RemovalPolicy.DESTROY,
>                       )
> 
>         cluster = CfnCluster(self, 'Cluster',
>                              cluster_type='single-node',
>                              db_name='dev',
>                              master_username='bevelvoerder',
>                              master_user_password='Wagw00rdEen',
>                              node_type='dc2.large',
>                              encrypted=True,
>                              kms_key_id=key.key_id,
>                              classic=True,
>                              )
>         cluster.apply_removal_policy(RemovalPolicy.DESTROY)

Recommend reopening this ticket for further consideration.

**Comment by rgoltz** [comment] 2023-02-10 17:28
@prerna-p Cloud you please re-open this issue, please?

**Comment by rgoltz** [comment] 2023-02-12 09:53
@CloudChoom Lucas / @kanitkah Harshu - Could you please re-open this issue, since this bug is still in place? The wrong status of this github issue affecting our tracking of false-positives of drift detection. Thanks!

**Comment by kanitkah** [comment] 2023-02-15 19:04
@rgoltz We will get this ticket reopened.

**Comment by shwetayakkali** [comment] 2023-03-20 18:01
Classic property is a writeOnly property, moving it under writeOnly will not have drift.

please confirm.

**Comment by rgoltz** [comment] 2023-03-23 09:31
@shwetayakkali I assume your question is more related to the underlying CFN implementation, which may be addressed in a linked issue under https://github.com/aws-cloudformation/aws-cloudformation-resource-providers-redshift ? (this worked really good with the RDS team in the past)

**Comment by mashuaihh** [comment] 2023-09-13 19:25
Verified that it's no longer an issue

**Closed** 2023-09-13 20:02 UTC
Labels: bug
