### ISSUE TITLE
AWS::RDS::DBInstance drift detection false positive on NetworkType

### ISSUE THREAD

**Issue by Tietew** [aws-cloudformation/cloudformation-coverage-roadmap#1393] opened 2022-11-10 12:30 UTC
### Name of the resource

AWS::RDS::DBInstance

### Issue Description

On a DB instance with `NetworkType: DUAL`, drift detection reports `NetworkType` is REMOVED.

### Expected Behavior

Expected in drift details shows following JSON:
```json
{
  "AllocatedStorage": 20,
  "AvailabilityZone": "ap-northeast-1a",
  "BackupRetentionPeriod": 30,
  "CopyTagsToSnapshot": true,
  "DBInstanceClass": "db.t4g.small",
  "DBParameterGroupName": "xxx",
  "DBSubnetGroupName": "xxx",
  "DeletionProtection": true,
  "EnableCloudwatchLogsExports": [
    "error",
    "general"
  ],
  "EnablePerformanceInsights": true,
  "Engine": "mysql",
  "EngineVersion": "8.0.30",
  "NetworkType": "DUAL",
  "PerformanceInsightsRetentionPeriod": 7,
  "PreferredBackupWindow": "18:13-18:43",
  "PreferredMaintenanceWindow": "Sun:19:13-Sun:19:43",
  "PubliclyAccessible": false,
  "StorageEncrypted": true,
  "StorageType": "gp2",
  "VPCSecurityGroups": [
    "sg-xxx"
  ]
}
```

### Observed Behavior

Actual in drift details shows following JSON (missing NetworkType):
```json
{
  "AllocatedStorage": 20,
  "AvailabilityZone": "ap-northeast-1a",
  "BackupRetentionPeriod": 30,
  "CopyTagsToSnapshot": true,
  "DBInstanceClass": "db.t4g.small",
  "DBParameterGroupName": "xxx",
  "DBSubnetGroupName": "xxx",
  "DeletionProtection": true,
  "EnableCloudwatchLogsExports": [
    "error",
    "general"
  ],
  "EnablePerformanceInsights": true,
  "Engine": "mysql",
  "EngineVersion": "8.0.30",
  "PerformanceInsightsRetentionPeriod": 7,
  "PreferredBackupWindow": "18:13-18:43",
  "PreferredMaintenanceWindow": "sun:19:13-sun:19:43",
  "PubliclyAccessible": false,
  "StorageEncrypted": true,
  "StorageType": "gp2",
  "VPCSecurityGroups": [
    "sg-xxx"
  ]
}
```

### Test Cases

Deploy a AWS::RDS::DBInstance with `NetworkType: "DUAL"`, then detect drift.

**Comment by osdrv** [comment] 2023-02-28 21:32
Our tests indicate the issue is completely fixed now. @Tietew any chance you could confirm this please?

**Comment by Tietew** [comment] 2023-03-02 04:03
@osdrv I have confirmed in ap-northeast-1. The drift status is now IN_SYNC. Thanks much!

**Comment by osdrv** [comment] 2023-03-02 11:36
@Tietew great news, thank you!

**Closed** 2023-03-02 12:03 UTC
Labels: bug
