### ISSUE TITLE
AWS::Elasticsearch::Domain - ElasticsearchClusterConfig-ExistingAttribute-NewOption

### ISSUE THREAD

**Issue by jpslav** [aws-cloudformation/cloudformation-coverage-roadmap#116] opened 2019-08-08 03:00 UTC
1. Title -> AWS::Elasticsearch::Domain-ElasticsearchClusterConfig-ExistingAttribute-NewOption
2. Scope of request -> Elasticsearch supports 3 instances across 3 AZs without dedicated masters, but when those options are set in Cloudformation (`ZoneAwarenessEnabled: "true"` and `InstanceCount: 3`), CloudFormation gives an event error saying "You must choose an even number of data nodes for a two Availability Zone deployment).  Seems like CloudFormation doesn't know that 3 AZ deployments are now a thing.  Request is to update CloudFormation internals to allow for this legal combination of settings.
3. Expected behavior -> An ES domain with 3 non-dedicated masters in 3 AZs should be allowed.
4. Category: Analytics
7. Additional context: See this [longer AWS forum post on the issue](https://forums.aws.amazon.com/message.jspa?messageID=895355#895355) (along with some +1's there by other folks).  Here's the [AWS blog post about 3-AZ Elasticsearch deployments](https://aws.amazon.com/about-aws/whats-new/2019/02/amazon-elasticsearch-service-now-supports-three-availability-zone-deployments/).

**Comment by irvingpop** [comment] 2019-08-08 14:50
I believe this is a dupe of #8

**Comment by steven-cuthill-otm** [comment] 2019-08-27 13:15
@luiseduardocolon dupe of #8

**Comment by jessedoyle** [comment] 2020-06-18 16:40
Just ran into this issue today! Why is so difficult to create a highly-available ES cluster with CloudFormation?

**Comment by TheDanBlanco** [comment] 2023-09-25 20:55
this seems to be fixed. if it's not, please re-open!

**Closed by TheDanBlanco** 2023-09-25 20:55 UTC
Labels: analytics
